# Generated by Django 3.1.12 on 2025-10-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='userview.geofence'),
        ),
        migrations.AlterField(
            model_name='class',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='userview.geofence'),
        ),
    ]
