# Generated by Django 3.1.12 on 2025-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_auto_20251025_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_instance', 'session_day'], name='att_cls_day_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'session_day'], name='att_std_day_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_instance', 'student', 'session_day'], name='att_cls_std_day_idx'),
        ),
    ]
