# Generated by Django 3.1.12 on 2025-11-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0003_auto_20251115_2210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
